CUDA_VISIBLE_DEVICES=0 python EPIC_main.py --method standard --persona_index 0 --mode stream --stream_seed 0 --output_dir stream_test --dataset PrefWiki --doc_mode wiki --llm_model_name Qwen/Qwen3-4B-Instruct-2507 --vllm_server_url 8067 --stream_batch_size 5000
CUDA_VISIBLE_DEVICES=0 python EPIC_main.py --method standard --persona_index 1 --mode stream --stream_seed 0 --output_dir stream_test --dataset PrefWiki --doc_mode wiki --llm_model_name Qwen/Qwen3-4B-Instruct-2507 --vllm_server_url 8067 --stream_batch_size 5000
CUDA_VISIBLE_DEVICES=0 python EPIC_main.py --method standard --persona_index 2 --mode stream --stream_seed 0 --output_dir stream_test --dataset PrefWiki --doc_mode wiki --llm_model_name Qwen/Qwen3-4B-Instruct-2507 --vllm_server_url 8067 --stream_batch_size 5000
CUDA_VISIBLE_DEVICES=0 python EPIC_main.py --method standard --persona_index 3 --mode stream --stream_seed 0 --output_dir stream_test --dataset PrefWiki --doc_mode wiki --llm_model_name Qwen/Qwen3-4B-Instruct-2507 --vllm_server_url 8067 --stream_batch_size 5000
CUDA_VISIBLE_DEVICES=0 python EPIC_main.py --method standard --persona_index 4 --mode stream --stream_seed 0 --output_dir stream_test --dataset PrefWiki --doc_mode wiki --llm_model_name Qwen/Qwen3-4B-Instruct-2507 --vllm_server_url 8067 --stream_batch_size 5000
CUDA_VISIBLE_DEVICES=0 python EPIC_main.py --method standard --persona_index 5 --mode stream --stream_seed 0 --output_dir stream_test --dataset PrefWiki --doc_mode wiki --llm_model_name Qwen/Qwen3-4B-Instruct-2507 --vllm_server_url 8067 --stream_batch_size 5000
CUDA_VISIBLE_DEVICES=0 python EPIC_main.py --method standard --persona_index 6 --mode stream --stream_seed 0 --output_dir stream_test --dataset PrefWiki --doc_mode wiki --llm_model_name Qwen/Qwen3-4B-Instruct-2507 --vllm_server_url 8067 --stream_batch_size 5000
CUDA_VISIBLE_DEVICES=0 python EPIC_main.py --method standard --persona_index 7 --mode stream --stream_seed 0 --output_dir stream_test --dataset PrefWiki --doc_mode wiki --llm_model_name Qwen/Qwen3-4B-Instruct-2507 --vllm_server_url 8067 --stream_batch_size 5000
CUDA_VISIBLE_DEVICES=0 python EPIC_main.py --method standard --persona_index 8 --mode stream --stream_seed 0 --output_dir stream_test --dataset PrefWiki --doc_mode wiki --llm_model_name Qwen/Qwen3-4B-Instruct-2507 --vllm_server_url 8067 --stream_batch_size 5000
CUDA_VISIBLE_DEVICES=0 python EPIC_main.py --method standard --persona_index 9 --mode stream --stream_seed 0 --output_dir stream_test --dataset PrefWiki --doc_mode wiki --llm_model_name Qwen/Qwen3-4B-Instruct-2507 --vllm_server_url 8067 --stream_batch_size 5000




# CUDA_VISIBLE_DEVICES=0 python EPIC_main.py --method standard --persona_index 1 --mode stream --stream_seed 0 --output_dir stream --dataset PrefWiki --doc_mode wiki --llm_model_name Qwen/Qwen3-4B-Instruct-2507 --vllm_server_url 8067 --stream_batch_size 5000
# CUDA_VISIBLE_DEVICES=0 python EPIC_main.py --method standard --persona_index 2 --mode stream --stream_seed 0 --output_dir stream --dataset PrefWiki --doc_mode wiki --llm_model_name Qwen/Qwen3-4B-Instruct-2507 --vllm_server_url 8067 --stream_batch_size 5000
# CUDA_VISIBLE_DEVICES=0 python EPIC_main.py --method standard --persona_index 3 --mode stream --stream_seed 0 --output_dir stream --dataset PrefWiki --doc_mode wiki --llm_model_name Qwen/Qwen3-4B-Instruct-2507 --vllm_server_url 8067 --stream_batch_size 5000
# CUDA_VISIBLE_DEVICES=0 python EPIC_main.py --method standard --persona_index 4 --mode stream --stream_seed 0 --output_dir stream --dataset PrefWiki --doc_mode wiki --llm_model_name Qwen/Qwen3-4B-Instruct-2507 --vllm_server_url 8067 --stream_batch_size 5000
# CUDA_VISIBLE_DEVICES=0 python EPIC_main.py --method standard --persona_index 5 --mode stream --stream_seed 0 --output_dir stream --dataset PrefWiki --doc_mode wiki --llm_model_name Qwen/Qwen3-4B-Instruct-2507 --vllm_server_url 8067 --stream_batch_size 5000
# CUDA_VISIBLE_DEVICES=0 python EPIC_main.py --method standard --persona_index 6 --mode stream --stream_seed 0 --output_dir stream --dataset PrefWiki --doc_mode wiki --llm_model_name Qwen/Qwen3-4B-Instruct-2507 --vllm_server_url 8067 --stream_batch_size 5000
# CUDA_VISIBLE_DEVICES=0 python EPIC_main.py --method standard --persona_index 7 --mode stream --stream_seed 0 --output_dir stream --dataset PrefWiki --doc_mode wiki --llm_model_name Qwen/Qwen3-4B-Instruct-2507 --vllm_server_url 8067 --stream_batch_size 5000
# CUDA_VISIBLE_DEVICES=0 python EPIC_main.py --method standard --persona_index 8 --mode stream --stream_seed 0 --output_dir stream --dataset PrefWiki --doc_mode wiki --llm_model_name Qwen/Qwen3-4B-Instruct-2507 --vllm_server_url 8067 --stream_batch_size 5000
# CUDA_VISIBLE_DEVICES=0 python EPIC_main.py --method standard --persona_index 9 --mode stream --stream_seed 0 --output_dir stream --dataset PrefWiki --doc_mode wiki --llm_model_name Qwen/Qwen3-4B-Instruct-2507 --vllm_server_url 8067 --stream_batch_size 5000

# python evaluate_stream_with_different_llm.py --base_dir stream_prefwiki/wiki/standard/ --vllm_url http://localhost:8045 --eval_model meta-llama/Llama-3.1-8B-Instruct