CUDA_VISIBLE_DEVICES=0 python EPIC_main.py --method cosine --persona_index 0 --stream_seed 0 --mode stream --output_dir stream_test --dataset PrefWiki --doc_mode wiki --llm_model_name Qwen/Qwen3-4B-Instruct-2507 --vllm_server_url 8067 --stream_batch_size 5000
CUDA_VISIBLE_DEVICES=0 python EPIC_main.py --method cosine --persona_index 1 --stream_seed 0 --mode stream --output_dir stream_test --dataset PrefWiki --doc_mode wiki --llm_model_name Qwen/Qwen3-4B-Instruct-2507 --vllm_server_url 8067 --stream_batch_size 5000
CUDA_VISIBLE_DEVICES=0 python EPIC_main.py --method cosine --persona_index 2 --stream_seed 0 --mode stream --output_dir stream_test --dataset PrefWiki --doc_mode wiki --llm_model_name Qwen/Qwen3-4B-Instruct-2507 --vllm_server_url 8067 --stream_batch_size 5000
CUDA_VISIBLE_DEVICES=0 python EPIC_main.py --method cosine --persona_index 3 --stream_seed 0 --mode stream --output_dir stream_test --dataset PrefWiki --doc_mode wiki --llm_model_name Qwen/Qwen3-4B-Instruct-2507 --vllm_server_url 8067 --stream_batch_size 5000
CUDA_VISIBLE_DEVICES=0 python EPIC_main.py --method cosine --persona_index 4 --stream_seed 0 --mode stream --output_dir stream_test --dataset PrefWiki --doc_mode wiki --llm_model_name Qwen/Qwen3-4B-Instruct-2507 --vllm_server_url 8067 --stream_batch_size 5000
CUDA_VISIBLE_DEVICES=0 python EPIC_main.py --method cosine --persona_index 5 --stream_seed 0 --mode stream --output_dir stream_test --dataset PrefWiki --doc_mode wiki --llm_model_name Qwen/Qwen3-4B-Instruct-2507 --vllm_server_url 8067 --stream_batch_size 5000
CUDA_VISIBLE_DEVICES=0 python EPIC_main.py --method cosine --persona_index 6 --stream_seed 0 --mode stream --output_dir stream_test --dataset PrefWiki --doc_mode wiki --llm_model_name Qwen/Qwen3-4B-Instruct-2507 --vllm_server_url 8067 --stream_batch_size 5000
CUDA_VISIBLE_DEVICES=0 python EPIC_main.py --method cosine --persona_index 7 --stream_seed 0 --mode stream --output_dir stream_test --dataset PrefWiki --doc_mode wiki --llm_model_name Qwen/Qwen3-4B-Instruct-2507 --vllm_server_url 8067 --stream_batch_size 5000
CUDA_VISIBLE_DEVICES=0 python EPIC_main.py --method cosine --persona_index 8 --stream_seed 0 --mode stream --output_dir stream_test --dataset PrefWiki --doc_mode wiki --llm_model_name Qwen/Qwen3-4B-Instruct-2507 --vllm_server_url 8067 --stream_batch_size 5000
CUDA_VISIBLE_DEVICES=0 python EPIC_main.py --method cosine --persona_index 9 --stream_seed 0 --mode stream --output_dir stream_test --dataset PrefWiki --doc_mode wiki --llm_model_name Qwen/Qwen3-4B-Instruct-2507 --vllm_server_url 8067 --stream_batch_size 5000

# CUDA_VISIBLE_DEVICES=0 python EPIC_main.py --method cosine --persona_index 1 --stream_seed 0 --mode stream --output_dir stream --dataset PrefWiki --doc_mode wiki --llm_model_name Qwen/Qwen3-4B-Instruct-2507 --vllm_server_url 8067 --stream_batch_size 5000
# CUDA_VISIBLE_DEVICES=0 python EPIC_main.py --method cosine --persona_index 2 --stream_seed 0 --mode stream --output_dir stream --dataset PrefWiki --doc_mode wiki --llm_model_name Qwen/Qwen3-4B-Instruct-2507 --vllm_server_url 8067 --stream_batch_size 5000
# CUDA_VISIBLE_DEVICES=0 python EPIC_main.py --method cosine --persona_index 3 --stream_seed 0 --mode stream --output_dir stream --dataset PrefWiki --doc_mode wiki --llm_model_name Qwen/Qwen3-4B-Instruct-2507 --vllm_server_url 8067 --stream_batch_size 5000
# CUDA_VISIBLE_DEVICES=0 python EPIC_main.py --method cosine --persona_index 4 --stream_seed 0 --mode stream --output_dir stream --dataset PrefWiki --doc_mode wiki --llm_model_name Qwen/Qwen3-4B-Instruct-2507 --vllm_server_url 8067 --stream_batch_size 5000
# CUDA_VISIBLE_DEVICES=0 python EPIC_main.py --method cosine --persona_index 5 --stream_seed 0 --mode stream --output_dir stream --dataset PrefWiki --doc_mode wiki --llm_model_name Qwen/Qwen3-4B-Instruct-2507 --vllm_server_url 8067 --stream_batch_size 5000
# CUDA_VISIBLE_DEVICES=0 python EPIC_main.py --method cosine --persona_index 6 --stream_seed 0 --mode stream --output_dir stream --dataset PrefWiki --doc_mode wiki --llm_model_name Qwen/Qwen3-4B-Instruct-2507 --vllm_server_url 8067 --stream_batch_size 5000
# CUDA_VISIBLE_DEVICES=0 python EPIC_main.py --method cosine --persona_index 7 --stream_seed 0 --mode stream --output_dir stream --dataset PrefWiki --doc_mode wiki --llm_model_name Qwen/Qwen3-4B-Instruct-2507 --vllm_server_url 8067 --stream_batch_size 5000
# CUDA_VISIBLE_DEVICES=0 python EPIC_main.py --method cosine --persona_index 8 --stream_seed 0 --mode stream --output_dir stream --dataset PrefWiki --doc_mode wiki --llm_model_name Qwen/Qwen3-4B-Instruct-2507 --vllm_server_url 8067 --stream_batch_size 5000
# CUDA_VISIBLE_DEVICES=0 python EPIC_main.py --method cosine --persona_index 9 --stream_seed 0 --mode stream --output_dir stream --dataset PrefWiki --doc_mode wiki --llm_model_name Qwen/Qwen3-4B-Instruct-2507 --vllm_server_url 8067 --stream_batch_size 5000

# python evaluate_stream_with_different_llm.py --base_dir stream_prefwiki/wiki/cosine/ --vllm_url http://localhost:8045 --eval_model meta-llama/Llama-3.1-8B-Instruct