CUDA_VISIBLE_DEVICES=0 python EPIC_main.py --method EPIC_inst --persona_index 0 --mode stream     --output_dir stream --dataset PrefEval --doc_mode lmsys_sampled    --llm_model_name Qwen/Qwen2.5-1.5B-Instruct --use_local_llm     --stream_batch_size 2000
CUDA_VISIBLE_DEVICES=0 python EPIC_main.py --method EPIC_inst --persona_index 1 --mode stream     --output_dir stream --dataset PrefEval --doc_mode lmsys_sampled    --llm_model_name Qwen/Qwen2.5-1.5B-Instruct --use_local_llm     --stream_batch_size 2000
CUDA_VISIBLE_DEVICES=0 python EPIC_main.py --method EPIC_inst --persona_index 2 --mode stream     --output_dir stream --dataset PrefEval --doc_mode lmsys_sampled    --llm_model_name Qwen/Qwen2.5-1.5B-Instruct --use_local_llm     --stream_batch_size 2000
CUDA_VISIBLE_DEVICES=0 python EPIC_main.py --method EPIC_inst --persona_index 3 --mode stream     --output_dir stream --dataset PrefEval --doc_mode lmsys_sampled    --llm_model_name Qwen/Qwen2.5-1.5B-Instruct --use_local_llm     --stream_batch_size 2000
CUDA_VISIBLE_DEVICES=0 python EPIC_main.py --method EPIC_inst --persona_index 4 --mode stream     --output_dir stream --dataset PrefEval --doc_mode lmsys_sampled    --llm_model_name Qwen/Qwen2.5-1.5B-Instruct --use_local_llm     --stream_batch_size 2000
CUDA_VISIBLE_DEVICES=0 python EPIC_main.py --method EPIC_inst --persona_index 5 --mode stream     --output_dir stream --dataset PrefEval --doc_mode lmsys_sampled    --llm_model_name Qwen/Qwen2.5-1.5B-Instruct --use_local_llm     --stream_batch_size 2000
CUDA_VISIBLE_DEVICES=0 python EPIC_main.py --method EPIC_inst --persona_index 6 --mode stream     --output_dir stream --dataset PrefEval --doc_mode lmsys_sampled    --llm_model_name Qwen/Qwen2.5-1.5B-Instruct --use_local_llm     --stream_batch_size 2000
CUDA_VISIBLE_DEVICES=0 python EPIC_main.py --method EPIC_inst --persona_index 7 --mode stream     --output_dir stream --dataset PrefEval --doc_mode lmsys_sampled    --llm_model_name Qwen/Qwen2.5-1.5B-Instruct --use_local_llm     --stream_batch_size 2000
CUDA_VISIBLE_DEVICES=0 python EPIC_main.py --method EPIC_inst --persona_index 8 --mode stream     --output_dir stream --dataset PrefEval --doc_mode lmsys_sampled    --llm_model_name Qwen/Qwen2.5-1.5B-Instruct --use_local_llm     --stream_batch_size 2000
CUDA_VISIBLE_DEVICES=0 python EPIC_main.py --method EPIC_inst --persona_index 9 --mode stream     --output_dir stream --dataset PrefEval --doc_mode lmsys_sampled    --llm_model_name Qwen/Qwen2.5-1.5B-Instruct --use_local_llm     --stream_batch_size 2000
python evaluate_stream_with_different_llm.py --base_dir stream_prefeval/lmsys_sampled/EPIC_inst/ --vllm_url http://localhost:8000 --eval_model meta-llama/Llama-3.1-8B-Instruct